### ISSUE TITLE
Epic TODO List

### ISSUE THREAD

**Issue by kgpoj** [kgpoj/happyHomework#1]
# Overview
Create a todo list component to manage todo items, users can use this component to easily record and manage todo items, so that they can organize their time more efficiently

# UI Design
![image](https://user-images.githubusercontent.com/73574762/218958189-41c03cf2-2ff5-4e94-9509-37541bb3d29e.png)

# Technical approach

- ## Data storage

>### Option 1: store the data as a state of the parent component
#### pros
- easy to start
#### cons
- could be difficult for nested components to get and set data
- data cannot be persisted

>### Option 2: session storage
#### pros
- easy to access the data
- data can be persisted
- data is reset when a new browser tab is opened, making it easier to prepare the data
#### cons
- may lose data when accidentally close the browser

>### Option 3: local storage
#### pros
- data remains even when the browser is closed
#### corns
- cannot reset the data to a initial state, not convenient for testing

- ## Component library

>### Option 1: using ant design
#### pros
- easy to use, save time
#### cons
- may need to change a lot of styles

>### Option 2: not using ant design
#### pros
- components can be more flexible
- a good chance to practice Typescript
#### cons
- need to write more files, folder structure can be complicated

# In Scope
- [ ] add new todo item
- [ ] edit todo item
- [ ] delete todo item
- [ ] mark todo item(as completed or active)
- [ ] filter todo items by status
- [ ] clear all completed items
- [ ] responsive design

# Out of Scope
- Interact with backend

# QA Strategy
1. Enter a new todo item in the input element and press `Enter`, make sure the new item appears in the list and the input is cleared.
2. Hover your mouse on an existing todo item, a delete button should appear, and when you click on it, the todo item is deleted
3. Click the checkbox on the left of a todo item, the item's state should be switched
4. When double click a todo item, it should become editable, and you can press `Enter` to confirm the update
5. There should be texts like `2 items left` at the left bottom, indicating how many todos there are in total(both active and completed)
6. Click All/Active/Completed, then items with corresponding status are filtered
7. Click `Clear Completed`, then all completed items should be removed from the list
8. When adding/editing todo item, if the new todo is empty, there should be a prompt message saying `Todo can not be empty`
9. todo very long

# Question
- folder structure
